usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/bluetooth/btchat/btchat
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/bluetooth/heartrate-game/heartrate-game
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/bluetooth/heartrate-server/heartrate-server
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/bluetooth/lowenergyscanner/lowenergyscanner
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/nfc/annotatedurl/annotatedurl
usr/lib/${DEB_HOST_MULTIARCH}/qt6/examples/nfc/ndefeditor/ndefeditor
